In [42]:
#panda series 
"""a series is one dimentional labled array capable of holding any data type . this axis labels are 
collectively called the index .
series are stack in vertical but array is store in horizontal 
"""

'a series is one dimentional labled array capable of holding any data type . this axis labels are \ncollectively called the index .\nseries are stack in vertical but array is store in horizontal \n'

In [43]:
#creating serires 
import numpy as np 
import pandas as pd

In [44]:
labels = ['a','b','c']
my_list = [10,20,30]
my_arr= np.array([10,20,30])
d = {1:10,2:20,3:30}

In [45]:
pd.Series(my_list)  # s should be capital

0    10
1    20
2    30
dtype: int64

In [46]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [47]:
pd.Series(my_arr)   #but you cannot send 2d array as series is 1d

0    10
1    20
2    30
dtype: int64

In [48]:
#data frame 
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [49]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [51]:
df= pd.DataFrame(data_list)
col = ["name","age","city","salary"]
df = pd.DataFrame(data_list, columns =col)
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [52]:
#selection and indexing of columns

In [53]:
df["name"]

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [54]:
df[["name","city"]]           #here we dont use index we use name instead

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [55]:
#creating new column

In [56]:
df["designation"]=["doctor","eng","teacher","dean"]

In [57]:
df

    name  age      city  salary designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000     teacher
3  Linda   42    London   85000        dean

In [58]:
#remove

In [59]:
df.drop("designation",axis = 1 )   #ye bs copy kr ke dikha raha hain actual data mein manuplution nahi hua hain 
                                   #if actual mein karna hai tb df.drop("designation",axis = 1,inplace = true )

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [60]:
#selecting rows

In [61]:
df.loc[0]  #loc is location

name               John
age                  28
city           New York
salary            65000
designation      doctor
Name: 0, dtype: object

In [62]:
#if index location then 
df.iloc[3]

name            Linda
age                42
city           London
salary          85000
designation      dean
Name: 3, dtype: object

In [63]:
df.loc[[0,3]]

    name  age      city  salary designation
0   John   28  New York   65000      doctor
3  Linda   42    London   85000        dean

In [64]:
#selecting subset of row and column
df.loc[[0,1]][["name","city"]]

   name      city
0  John  New York
1  Anna     Paris

#condition selection

In [65]:
df[df["age"] > 30]

    name  age    city  salary designation
1   Anna   34   Paris   70000         eng
3  Linda   42  London   85000        dean

In [66]:
df[(df["age"] > 30) & (df["city"] == "Paris") ]   #use proper bracket and & is used as and

   name  age   city  salary designation
1  Anna   34  Paris   70000         eng

In [67]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [68]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [69]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [70]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [71]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [72]:
#removing missing data

In [73]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [74]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [75]:
#filling the missing data

In [76]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [77]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [78]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [79]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [80]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

salaries

In [81]:
pd.merge(employees,salaries,on='employee_id',how ='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [82]:
pd.merge(employees,salaries,on='employee_id',how ='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [83]:
pd.merge(employees,salaries,on='employee_id',how ='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [84]:
pd.merge(employees,salaries,on='employee_id',how ='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [85]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [86]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [87]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [88]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [89]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [92]:
# **joining 2 data frame **

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [93]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [94]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [96]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

**group by **

In [97]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [99]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [100]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [101]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [102]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

aggegration

In [103]:
df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [104]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [105]:
#pivot table
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    170     96   John  January      Q1
1  2023-01-02       B   West    319     78   Mary  January      Q1
2  2023-01-03       C  North    509     74    Bob  January      Q1
3  2023-01-04       D  South    169     98  Alice  January      Q1
4  2023-01-05       A   East    781     47   John  January      Q1
5  2023-01-06       B   West    994     53   Mary  January      Q1
6  2023-01-07       C  North    682     71    Bob  January      Q1
7  2023-01-08       D  South    421     95  Alice  January      Q1
8  2023-01-09       A   East    451     84   John  January      Q1
9  2023-01-10       B   West    922     33   Mary  January      Q1
10 2023-01-11       C  North    612     93    Bob  January      Q1
11 2023-01-12       D  South    771     35  Alice  January      Q1
12 2023-01-13       A   East    949     82   John  January      Q1
13 2023-01-14       B   West    282     33   Mary  January      Q1
14 2023-01-15       C  North    211     27    Bob  January      Q1
15 2023-01-16       D  South    215     27  Alice  January      Q1
16 2023-01-17       A   East    100     64   John  January      Q1
17 2023-01-18       B   West    477     52   Mary  January      Q1
18 2023-01-19       C  North    181     94    Bob  January      Q1
19 2023-01-20       D  South    781     59  Alice  January      Q1

In [106]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     451.0    NaN    NaN    NaN
North      NaN    NaN  509.0    NaN
South      NaN    NaN    NaN  421.0
West       NaN  477.0    NaN    NaN

In [107]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     490.2    NaN    NaN    NaN  74.6   NaN   NaN   NaN
North      NaN    NaN  439.0    NaN   NaN   NaN  71.8   NaN
South      NaN    NaN    NaN  471.4   NaN   NaN   NaN  62.8
West       NaN  598.8    NaN    NaN   NaN  49.8   NaN   NaN

In [108]:
#cross table

In [109]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [114]:
#operation
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [115]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [116]:
df1.shape

(5, 3)

In [117]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [118]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [119]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [120]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [121]:
#data frame applying function

In [122]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [123]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500